### ISSUE TITLE
Some registry values may require string

### ISSUE THREAD

**Issue by mikedzikowski** [Crombell95/UserRegistryDSC#3]
Issue:

Some HKCU settings may require string:

Example:
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logoff\0\0

Example:

  UserRegistry LogOffScript {
            Key       = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\Scripts\Logoff\0\0"
            ValueName = 'Script'
            ValueType = 'String'
            ValueData = 'C:\MyFolder\Set-Deallocation.ps1'
        }

This does not compile because ValueData expects an int

**Comment by Crombell95** [comment]
Thanks for your feedback! I have changed the ValueData type to string. This works for both string and int and also solves the issue.
